# Generated by Django 5.1.3 on 2024-11-06 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appeal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appeal',
            old_name='name',
            new_name='full_name',
        ),
    ]
