# Generated by Django 5.1.3 on 2024-11-06 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeal', '0002_rename_name_appeal_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
