# Generated by Django 5.1.3 on 2024-11-13 11:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appeal', '0003_alter_appeal_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='message',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
