# Generated by Django 5.1.3 on 2024-11-11 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_fact_link_navbar_slider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='body',
            field=models.TextField(),
        ),
    ]
