# Generated by Django 5.1.3 on 2024-11-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_menuitem_delete_navbar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Helpline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('federation_number', models.CharField(max_length=100)),
                ('satate_number', models.CharField(max_length=100)),
            ],
        ),
    ]
