# Generated by Django 5.1.3 on 2024-11-11 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_helpline'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpline',
            name='federation_title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='helpline',
            name='state_title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='helpline',
            name='tag',
            field=models.CharField(default='', max_length=200),
        ),
    ]
