# Generated by Django 5.1.3 on 2024-11-11 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_remove_link_head'),
    ]

    operations = [
        migrations.RenameField(
            model_name='helpline',
            old_name='satate_number',
            new_name='state_number',
        ),
    ]
