# Generated by Django 5.1.3 on 2024-11-12 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_alter_menu_options_alter_menuitem_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='parent',
        ),
    ]
