# Generated by Django 5.1.3 on 2024-11-12 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_menuitem_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
