# Generated by Django 5.1.3 on 2024-11-12 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_menu_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=100)),
                ('short_content', models.TextField()),
                ('title', models.CharField(max_length=200)),
                ('federation_content', models.CharField(default='', max_length=200)),
                ('federation_number', models.CharField(max_length=100)),
                ('state_content', models.CharField(max_length=200)),
                ('state_number', models.CharField(max_length=100)),
            ],
        ),
    ]
