# Generated by Django 5.1.3 on 2024-11-13 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_alter_menu_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Url'),
        ),
    ]
