# Generated by Django 5.1.3 on 2024-11-13 11:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_fact_body_en_fact_body_ru_fact_body_uz_fact_title_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='short_content',
            field=ckeditor.fields.RichTextField(blank=True, max_length=200, verbose_name='short_content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='short_content_en',
            field=ckeditor.fields.RichTextField(blank=True, max_length=200, null=True, verbose_name='short_content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='short_content_ru',
            field=ckeditor.fields.RichTextField(blank=True, max_length=200, null=True, verbose_name='short_content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='short_content_uz',
            field=ckeditor.fields.RichTextField(blank=True, max_length=200, null=True, verbose_name='short_content'),
        ),
    ]
