# Generated by Django 5.1.3 on 2024-11-15 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0025_alter_post_short_content_alter_post_short_content_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='call',
            options={'verbose_name': 'Call', 'verbose_name_plural': 'Calls'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='fact',
            options={'verbose_name': 'Fact', 'verbose_name_plural': 'Facts'},
        ),
        migrations.AlterModelOptions(
            name='helpline',
            options={'verbose_name': 'Helpline', 'verbose_name_plural': 'Helplines'},
        ),
        migrations.AlterModelOptions(
            name='link',
            options={'verbose_name': 'Link', 'verbose_name_plural': 'Links'},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'Menu', 'verbose_name_plural': 'Menus'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name': 'Slider', 'verbose_name_plural': 'Sliders'},
        ),
    ]
