# Generated by Django 5.1.3 on 2024-11-26 06:10

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0033_remove_call_federation_content_af_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='body',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='title',
        ),
        migrations.CreateModel(
            name='SliderTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ru', 'Russian'), ('en', 'English'), ('fr', 'French')], max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('body', ckeditor.fields.RichTextField()),
                ('slider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='posts.slider')),
            ],
            options={
                'verbose_name': 'Slider Translation',
                'verbose_name_plural': 'Slider Translations',
                'unique_together': {('slider', 'language')},
            },
        ),
    ]
