# Generated by Django 5.1.3 on 2024-11-26 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
        ('posts', '0034_remove_slider_body_remove_slider_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slidertranslation',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.language'),
        ),
    ]
