# Generated by Django 5.1.3 on 2024-11-28 06:16

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=25, null=True)),
                ('title', models.CharField(default='', max_length=300)),
                ('detail', ckeditor.fields.RichTextField(default='', verbose_name='detail')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
            },
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_body', ckeditor.fields.RichTextField(verbose_name='question body')),
                ('answer_body', ckeditor.fields.RichTextField(verbose_name='answer body')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Question Asnswer',
                'verbose_name_plural': 'Questions Answers',
            },
        ),
    ]
