# Generated by Django 5.1.3 on 2024-11-06 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_remove_question_user_question_number_delete_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
