# Generated by Django 5.1.3 on 2024-11-13 11:04

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_alter_question_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='detail_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='detail_ru',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='detail_uz',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='title_en',
            field=models.CharField(max_length=300, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='question',
            name='title_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='question',
            name='title_uz',
            field=models.CharField(max_length=300, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='question',
            name='detail',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=300, verbose_name='title'),
        ),
    ]
