# Generated by Django 5.1.3 on 2024-11-13 11:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_question_detail_en_question_detail_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='detail',
            field=ckeditor.fields.RichTextField(verbose_name='detail'),
        ),
        migrations.AlterField(
            model_name='question',
            name='detail_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='detail'),
        ),
        migrations.AlterField(
            model_name='question',
            name='detail_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='detail'),
        ),
        migrations.AlterField(
            model_name='question',
            name='detail_uz',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='detail'),
        ),
    ]
