# Generated by Django 5.1.3 on 2024-11-19 05:31

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0007_remove_question_detail_remove_question_detail_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='content',
        ),
        migrations.AddField(
            model_name='question',
            name='detail',
            field=ckeditor.fields.RichTextField(default='', verbose_name='detail'),
        ),
        migrations.AddField(
            model_name='question',
            name='number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='title',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
