# Generated by Django 5.1.3 on 2024-11-19 05:51

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0008_remove_question_content_question_detail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=25, null=True)),
                ('title', models.CharField(default='', max_length=300)),
                ('detail', ckeditor.fields.RichTextField(default='', verbose_name='detail')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
            },
        ),
        migrations.RenameField(
            model_name='question',
            old_name='add_time',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='question',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='question',
            name='number',
        ),
        migrations.RemoveField(
            model_name='question',
            name='title',
        ),
        migrations.AddField(
            model_name='question',
            name='body',
            field=ckeditor.fields.RichTextField(default='', verbose_name='body'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField(default='', verbose_name='Content')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Is Approved')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='question.question', verbose_name='Question')),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answers',
                'ordering': ['-created_at'],
            },
        ),
    ]
