# Generated by Django 5.1.3 on 2024-11-19 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0011_questionanswer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionanswer',
            options={'verbose_name': 'Question Asnswer', 'verbose_name_plural': 'Questions Answers'},
        ),
    ]
