# Generated by Django 5.1.3 on 2024-11-20 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0012_alter_questionanswer_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswer',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
    ]
