# Generated by Django 5.1.3 on 2024-11-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_filecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='body',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='FileCategory',
        ),
    ]
