# Generated by Django 5.1.3 on 2024-11-15 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_document_body_en_document_body_ru_document_body_uz_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Document', 'verbose_name_plural': 'Documents'},
        ),
    ]
