# Generated by Django 5.1.3 on 2024-11-21 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0008_alter_document_options_document_language'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Document', 'verbose_name_plural': 'Documents'},
        ),
        migrations.RemoveField(
            model_name='document',
            name='language',
        ),
    ]
